# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_nonlineal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 130)
        Form.setStyleSheet("*{\n"
"border: none;\n"
"padding: 0px;\n"
"margin: 0px;\n"
"font: 57 9pt \"Inter Medium\";\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #C0C0C0;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover, QLineEdit:focus {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid #C0C0C0;\n"
"    border-radius: 4px;\n"
"    background-color: #FFFFFF;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QComboBox:hover, QComboBox:focus {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container_nolineal = QtWidgets.QFrame(Form)
        self.container_nolineal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_nolineal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_nolineal.setObjectName("container_nolineal")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.container_nolineal)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.content_all_inputs = QtWidgets.QFrame(self.container_nolineal)
        self.content_all_inputs.setMaximumSize(QtCore.QSize(200, 16777215))
        self.content_all_inputs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_all_inputs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_all_inputs.setObjectName("content_all_inputs")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content_all_inputs)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.content_potencia = QtWidgets.QFrame(self.content_all_inputs)
        self.content_potencia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_potencia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_potencia.setObjectName("content_potencia")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_potencia)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.potencia_frame_container = QtWidgets.QFrame(self.content_potencia)
        self.potencia_frame_container.setMaximumSize(QtCore.QSize(16777215, 25))
        self.potencia_frame_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.potencia_frame_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.potencia_frame_container.setObjectName("potencia_frame_container")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.potencia_frame_container)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.potencia_label = QtWidgets.QLabel(self.potencia_frame_container)
        self.potencia_label.setObjectName("potencia_label")
        self.verticalLayout_6.addWidget(self.potencia_label)
        self.verticalLayout_4.addWidget(self.potencia_frame_container)
        self.frame_7 = QtWidgets.QFrame(self.content_potencia)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.potencia_entry = QtWidgets.QLineEdit(self.frame_7)
        self.potencia_entry.setMaximumSize(QtCore.QSize(80, 16777215))
        self.potencia_entry.setObjectName("potencia_entry")
        self.horizontalLayout.addWidget(self.potencia_entry)
        self.unidad_potencia_combo = QtWidgets.QComboBox(self.frame_7)
        self.unidad_potencia_combo.setMaximumSize(QtCore.QSize(50, 16777215))
        self.unidad_potencia_combo.setObjectName("unidad_potencia_combo")
        self.unidad_potencia_combo.addItem("")
        self.unidad_potencia_combo.addItem("")
        self.horizontalLayout.addWidget(self.unidad_potencia_combo)
        spacerItem = QtWidgets.QSpacerItem(215, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_3.addWidget(self.content_potencia)
        self.content_pulsos = QtWidgets.QFrame(self.content_all_inputs)
        self.content_pulsos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_pulsos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_pulsos.setObjectName("content_pulsos")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.content_pulsos)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pulsos_label = QtWidgets.QLabel(self.content_pulsos)
        self.pulsos_label.setObjectName("pulsos_label")
        self.verticalLayout_5.addWidget(self.pulsos_label)
        self.pulsos_combo = QtWidgets.QComboBox(self.content_pulsos)
        self.pulsos_combo.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pulsos_combo.setObjectName("pulsos_combo")
        self.pulsos_combo.addItem("")
        self.pulsos_combo.addItem("")
        self.pulsos_combo.addItem("")
        self.verticalLayout_5.addWidget(self.pulsos_combo)
        self.verticalLayout_3.addWidget(self.content_pulsos)
        self.content_equipo = QtWidgets.QFrame(self.content_all_inputs)
        self.content_equipo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_equipo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_equipo.setObjectName("content_equipo")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.content_equipo)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.content_equipo)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.content_equipo)
        self.comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox)
        self.verticalLayout_3.addWidget(self.content_equipo)
        self.horizontalLayout_2.addWidget(self.content_all_inputs)
        self.frame = QtWidgets.QFrame(self.container_nolineal)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.fp_non_lineal = QtWidgets.QLineEdit(self.frame_2)
        self.fp_non_lineal.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fp_non_lineal.setObjectName("fp_non_lineal")
        self.verticalLayout_2.addWidget(self.fp_non_lineal)
        self.verticalLayout_9.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.eficiencia_non_lineal = QtWidgets.QLineEdit(self.frame_3)
        self.eficiencia_non_lineal.setMaximumSize(QtCore.QSize(80, 16777215))
        self.eficiencia_non_lineal.setObjectName("eficiencia_non_lineal")
        self.verticalLayout_8.addWidget(self.eficiencia_non_lineal)
        self.verticalLayout_9.addWidget(self.frame_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.container_nolineal)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.potencia_label.setText(_translate("Form", "Potencia**"))
        self.unidad_potencia_combo.setItemText(0, _translate("Form", "kVA"))
        self.unidad_potencia_combo.setItemText(1, _translate("Form", "kW"))
        self.pulsos_label.setText(_translate("Form", "Número de pulsos**"))
        self.pulsos_combo.setItemText(0, _translate("Form", "4"))
        self.pulsos_combo.setItemText(1, _translate("Form", "6"))
        self.pulsos_combo.setItemText(2, _translate("Form", "12"))
        self.label_3.setText(_translate("Form", "Equipo**"))
        self.comboBox.setItemText(0, _translate("Form", "UPS"))
        self.comboBox.setItemText(1, _translate("Form", "TELECOM"))
        self.comboBox.setItemText(2, _translate("Form", "MEDIA (TV, Radio, ...)"))
        self.comboBox.setItemText(3, _translate("Form", "HORNO ELÉCTRICO"))
        self.label.setText(_translate("Form", "Factor de potencia"))
        self.label_2.setText(_translate("Form", "Eficiencia (%)"))
