# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_resistencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(363, 124)
        Form.setStyleSheet("*{\n"
"border: none;\n"
"padding: 0px;\n"
"margin: 0px;\n"
"font: 57 10pt \"Inter Medium\";\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #C0C0C0;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover, QLineEdit:focus {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid #C0C0C0;\n"
"    border-radius: 4px;\n"
"    background-color: #FFFFFF;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QComboBox:hover, QComboBox:focus {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container_resistencia = QtWidgets.QFrame(Form)
        self.container_resistencia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_resistencia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_resistencia.setObjectName("container_resistencia")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.container_resistencia)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.content_potencia = QtWidgets.QFrame(self.container_resistencia)
        self.content_potencia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_potencia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_potencia.setObjectName("content_potencia")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content_potencia)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.content_label_potencia = QtWidgets.QFrame(self.content_potencia)
        self.content_label_potencia.setMaximumSize(QtCore.QSize(16777215, 25))
        self.content_label_potencia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_label_potencia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_label_potencia.setObjectName("content_label_potencia")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_label_potencia)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.potencia_label = QtWidgets.QLabel(self.content_label_potencia)
        self.potencia_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.potencia_label.setObjectName("potencia_label")
        self.verticalLayout_4.addWidget(self.potencia_label)
        self.verticalLayout_3.addWidget(self.content_label_potencia)
        self.fcontent_potencia_resistencia = QtWidgets.QFrame(self.content_potencia)
        self.fcontent_potencia_resistencia.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fcontent_potencia_resistencia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fcontent_potencia_resistencia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fcontent_potencia_resistencia.setObjectName("fcontent_potencia_resistencia")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fcontent_potencia_resistencia)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.potencia_entry = QtWidgets.QLineEdit(self.fcontent_potencia_resistencia)
        self.potencia_entry.setMaximumSize(QtCore.QSize(50, 16777215))
        self.potencia_entry.setObjectName("potencia_entry")
        self.horizontalLayout.addWidget(self.potencia_entry)
        self.unidad_label = QtWidgets.QLabel(self.fcontent_potencia_resistencia)
        self.unidad_label.setObjectName("unidad_label")
        self.horizontalLayout.addWidget(self.unidad_label)
        spacerItem = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.fcontent_potencia_resistencia)
        self.verticalLayout_2.addWidget(self.content_potencia)
        self.content_fases_resistencia = QtWidgets.QFrame(self.container_resistencia)
        self.content_fases_resistencia.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.content_fases_resistencia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_fases_resistencia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_fases_resistencia.setObjectName("content_fases_resistencia")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content_fases_resistencia)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fases_label = QtWidgets.QLabel(self.content_fases_resistencia)
        self.fases_label.setObjectName("fases_label")
        self.horizontalLayout_2.addWidget(self.fases_label)
        self.fases_combo = QtWidgets.QComboBox(self.content_fases_resistencia)
        self.fases_combo.setObjectName("fases_combo")
        self.fases_combo.addItem("")
        self.fases_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.fases_combo)
        spacerItem1 = QtWidgets.QSpacerItem(145, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.content_fases_resistencia)
        self.content_fp_resistencia = QtWidgets.QFrame(self.container_resistencia)
        self.content_fp_resistencia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_fp_resistencia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_fp_resistencia.setObjectName("content_fp_resistencia")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.content_fp_resistencia)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fp_label = QtWidgets.QLabel(self.content_fp_resistencia)
        self.fp_label.setObjectName("fp_label")
        self.horizontalLayout_3.addWidget(self.fp_label)
        self.fp_entry = QtWidgets.QLineEdit(self.content_fp_resistencia)
        self.fp_entry.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fp_entry.setObjectName("fp_entry")
        self.horizontalLayout_3.addWidget(self.fp_entry)
        self.fp_ad_atr = QtWidgets.QComboBox(self.content_fp_resistencia)
        self.fp_ad_atr.setMinimumSize(QtCore.QSize(85, 0))
        self.fp_ad_atr.setMaximumSize(QtCore.QSize(85, 16777215))
        self.fp_ad_atr.setObjectName("fp_ad_atr")
        self.fp_ad_atr.addItem("")
        self.fp_ad_atr.addItem("")
        self.horizontalLayout_3.addWidget(self.fp_ad_atr)
        spacerItem2 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.content_fp_resistencia)
        self.verticalLayout.addWidget(self.container_resistencia)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.potencia_label.setText(_translate("Form", "Potencia**"))
        self.unidad_label.setText(_translate("Form", "kVA"))
        self.fases_label.setText(_translate("Form", "Fases"))
        self.fases_combo.setItemText(0, _translate("Form", "1"))
        self.fases_combo.setItemText(1, _translate("Form", "3"))
        self.fp_label.setText(_translate("Form", "Factor de potencia"))
        self.fp_ad_atr.setItemText(0, _translate("Form", "Inductivo"))
        self.fp_ad_atr.setItemText(1, _translate("Form", "Capacitivo"))
