# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_lum.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(271, 162)
        Form.setStyleSheet("*{\n"
"border: none;\n"
"padding: 0px;\n"
"margin: 0px;\n"
"font: 57 10pt \"Inter Medium\";\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #C0C0C0;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QLineEdit:hover, QLineEdit:focus {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid #C0C0C0;\n"
"    border-radius: 4px;\n"
"    background-color: #FFFFFF;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QComboBox:hover, QComboBox:focus {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content_main_iluminacion = QtWidgets.QFrame(Form)
        self.content_main_iluminacion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_main_iluminacion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_main_iluminacion.setObjectName("content_main_iluminacion")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.content_main_iluminacion)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.content_potencia = QtWidgets.QFrame(self.content_main_iluminacion)
        self.content_potencia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_potencia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_potencia.setObjectName("content_potencia")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content_potencia)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.content_potencia)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.content_potencia_unidad = QtWidgets.QFrame(self.content_potencia)
        self.content_potencia_unidad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_potencia_unidad.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_potencia_unidad.setObjectName("content_potencia_unidad")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content_potencia_unidad)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.potencia_iluminacion = QtWidgets.QLineEdit(self.content_potencia_unidad)
        self.potencia_iluminacion.setMaximumSize(QtCore.QSize(50, 16777215))
        self.potencia_iluminacion.setObjectName("potencia_iluminacion")
        self.horizontalLayout.addWidget(self.potencia_iluminacion)
        self.unidad_iluminacion = QtWidgets.QComboBox(self.content_potencia_unidad)
        self.unidad_iluminacion.setMaximumSize(QtCore.QSize(50, 16777215))
        self.unidad_iluminacion.setObjectName("unidad_iluminacion")
        self.unidad_iluminacion.addItem("")
        self.unidad_iluminacion.addItem("")
        self.horizontalLayout.addWidget(self.unidad_iluminacion)
        spacerItem = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.content_potencia_unidad)
        self.verticalLayout_5.addWidget(self.content_potencia)
        self.content_tipo = QtWidgets.QFrame(self.content_main_iluminacion)
        self.content_tipo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_tipo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_tipo.setObjectName("content_tipo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_tipo)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.content_tipo)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.content_tipo_2 = QtWidgets.QFrame(self.content_tipo)
        self.content_tipo_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_tipo_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_tipo_2.setObjectName("content_tipo_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content_tipo_2)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tipo_iluminacion = QtWidgets.QComboBox(self.content_tipo_2)
        self.tipo_iluminacion.setMinimumSize(QtCore.QSize(100, 0))
        self.tipo_iluminacion.setMaximumSize(QtCore.QSize(120, 16777215))
        self.tipo_iluminacion.setObjectName("tipo_iluminacion")
        self.tipo_iluminacion.addItem("")
        self.tipo_iluminacion.addItem("")
        self.tipo_iluminacion.addItem("")
        self.tipo_iluminacion.addItem("")
        self.horizontalLayout_2.addWidget(self.tipo_iluminacion)
        spacerItem1 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.content_tipo_2)
        self.verticalLayout_5.addWidget(self.content_tipo)
        self.contenedor_fp = QtWidgets.QFrame(self.content_main_iluminacion)
        self.contenedor_fp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_fp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_fp.setObjectName("contenedor_fp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contenedor_fp)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.contenedor_fp)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.contenedor_entry_fp = QtWidgets.QFrame(self.contenedor_fp)
        self.contenedor_entry_fp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor_entry_fp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor_entry_fp.setObjectName("contenedor_entry_fp")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.contenedor_entry_fp)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fp_lum = QtWidgets.QLineEdit(self.contenedor_entry_fp)
        self.fp_lum.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fp_lum.setObjectName("fp_lum")
        self.horizontalLayout_3.addWidget(self.fp_lum)
        spacerItem2 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.contenedor_entry_fp)
        self.verticalLayout_5.addWidget(self.contenedor_fp)
        self.verticalLayout.addWidget(self.content_main_iluminacion)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Potencia**"))
        self.unidad_iluminacion.setItemText(0, _translate("Form", "kW"))
        self.unidad_iluminacion.setItemText(1, _translate("Form", "kVA"))
        self.label_2.setText(_translate("Form", "Tipo de iluminación**"))
        self.tipo_iluminacion.setItemText(0, _translate("Form", "LED"))
        self.tipo_iluminacion.setItemText(1, _translate("Form", "Fluorescente"))
        self.tipo_iluminacion.setItemText(2, _translate("Form", "Incandescente"))
        self.tipo_iluminacion.setItemText(3, _translate("Form", "HID"))
        self.label_3.setText(_translate("Form", "Factor de potencia"))
