# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_simple_skin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 100)
        Dialog.setMinimumSize(QtCore.QSize(380, 100))
        Dialog.setMaximumSize(QtCore.QSize(380, 250))
        Dialog.setStyleSheet("*{\n"
"    border: none;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    font: 57 8pt \"Inter Medium\";\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: black;\n"
"}\n"
"\n"
"#dialog_cerrar{\n"
"    background-color:none;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"#dialog_cerrar:hover{\n"
"    background-color: rgb(167, 167, 167);\n"
"}\n"
"#dialog_cerrar:pressed{\n"
"    background-color: rgb(130, 130, 130);\n"
"}\n"
"\n"
" QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    font: 57 8pt \"Inter Medium\";\n"
"    padding: 5px;\n"
"    border: 1px solid gray;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 1px solid #0078D7;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(171, 171, 171);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#plain_text_report{\n"
"    border: 1px solid rgb(173, 173, 173);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("#frame{\n"
"    \n"
"    background-color: rgb(247, 247, 247);\n"
"    border: 1px solid gray;\n"
"    border-radius: 8px;\n"
"}")
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.icon_dialog = QtWidgets.QLabel(self.frame_4)
        self.icon_dialog.setText("")
        self.icon_dialog.setPixmap(QtGui.QPixmap("./resourses/img/dialog_information_icon.png"))
        self.icon_dialog.setScaledContents(False)
        self.icon_dialog.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_dialog.setObjectName("icon_dialog")
        self.verticalLayout_3.addWidget(self.icon_dialog)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 4, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mess_title = QtWidgets.QLabel(self.frame_6)
        self.mess_title.setMinimumSize(QtCore.QSize(0, 20))
        self.mess_title.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.mess_title.setFont(font)
        self.mess_title.setObjectName("mess_title")
        self.horizontalLayout_4.addWidget(self.mess_title)
        self.dialog_cerrar = QtWidgets.QToolButton(self.frame_6)
        self.dialog_cerrar.setMinimumSize(QtCore.QSize(20, 20))
        self.dialog_cerrar.setMaximumSize(QtCore.QSize(20, 20))
        self.dialog_cerrar.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dialog_cerrar.setIcon(icon)
        self.dialog_cerrar.setIconSize(QtCore.QSize(10, 10))
        self.dialog_cerrar.setObjectName("dialog_cerrar")
        self.horizontalLayout_4.addWidget(self.dialog_cerrar)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.mess_info = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.mess_info.setFont(font)
        self.mess_info.setWordWrap(True)
        self.mess_info.setObjectName("mess_info")
        self.verticalLayout_2.addWidget(self.mess_info)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_2)
        self.message_box_custom = QtWidgets.QFrame(self.frame)
        self.message_box_custom.setStyleSheet("")
        self.message_box_custom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.message_box_custom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.message_box_custom.setObjectName("message_box_custom")
        self.custom_frame_layout = QtWidgets.QVBoxLayout(self.message_box_custom)
        self.custom_frame_layout.setContentsMargins(4, 4, 4, 4)
        self.custom_frame_layout.setSpacing(0)
        self.custom_frame_layout.setObjectName("custom_frame_layout")
        self.plain_text_report = QtWidgets.QPlainTextEdit(self.message_box_custom)
        self.plain_text_report.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plain_text_report.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plain_text_report.setObjectName("plain_text_report")
        self.custom_frame_layout.addWidget(self.plain_text_report)
        self.verticalLayout.addWidget(self.message_box_custom)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(211, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.mess_button_box = QtWidgets.QDialogButtonBox(self.frame_3)
        self.mess_button_box.setMinimumSize(QtCore.QSize(0, 25))
        self.mess_button_box.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.mess_button_box.setFont(font)
        self.mess_button_box.setStyleSheet("")
        self.mess_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.mess_button_box.setObjectName("mess_button_box")
        self.horizontalLayout_3.addWidget(self.mess_button_box)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mess_title.setText(_translate("Dialog", "Título del mensaje"))
        self.dialog_cerrar.setText(_translate("Dialog", "..."))
        self.mess_info.setText(_translate("Dialog", "Información del mensaje"))
