# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skin_temp_mess.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(340, 69)
        Form.setMaximumSize(QtCore.QSize(340, 70))
        Form.setStyleSheet("*{\n"
"    padding:0px;\n"
"    margin:0px;\n"
"    border: none;\n"
"    font: 57 8pt \"Inter Medium\";\n"
"    background: rgb(60, 63, 65);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"#From{\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#container{\n"
"    border: 1px solid rgb(133, 136, 138);\n"
"}\n"
"\n"
"#title_mess{\n"
"    font: 63 8pt \"Inter SemiBold\";\n"
"}\n"
"\n"
"#close_button{\n"
"    image: url(img/cerrar_white.png);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#close_button:hover{\n"
"    background-color: rgb(42, 42, 43);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QFrame(Form)
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_container = QtWidgets.QFrame(self.container)
        self.icon_container.setMinimumSize(QtCore.QSize(60, 0))
        self.icon_container.setMaximumSize(QtCore.QSize(60, 16777215))
        self.icon_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_container.setObjectName("icon_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icon_container)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.icon = QtWidgets.QLabel(self.icon_container)
        self.icon.setMinimumSize(QtCore.QSize(50, 50))
        self.icon.setMaximumSize(QtCore.QSize(50, 50))
        self.icon.setText("")
        self.icon.setScaledContents(True)
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setObjectName("icon")
        self.verticalLayout_4.addWidget(self.icon)
        self.horizontalLayout.addWidget(self.icon_container)
        self.mess_container = QtWidgets.QFrame(self.container)
        self.mess_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mess_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mess_container.setObjectName("mess_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mess_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.container_title_button = QtWidgets.QFrame(self.mess_container)
        self.container_title_button.setMinimumSize(QtCore.QSize(0, 30))
        self.container_title_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.container_title_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_title_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_title_button.setObjectName("container_title_button")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.container_title_button)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_mess = QtWidgets.QLabel(self.container_title_button)
        self.title_mess.setObjectName("title_mess")
        self.horizontalLayout_2.addWidget(self.title_mess)
        spacerItem = QtWidgets.QSpacerItem(151, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.close_button = QtWidgets.QToolButton(self.container_title_button)
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.verticalLayout_2.addWidget(self.container_title_button)
        self.container_error_mess = QtWidgets.QFrame(self.mess_container)
        self.container_error_mess.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_error_mess.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_error_mess.setObjectName("container_error_mess")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.container_error_mess)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.container_error_mess)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.container_error_mess)
        self.horizontalLayout.addWidget(self.mess_container)
        self.verticalLayout.addWidget(self.container)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_mess.setText(_translate("Form", "Título del mensaje "))
        self.label.setText(_translate("Form", "Contenido del mensaje de error."))
