# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skin_splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 350)
        MainWindow.setMinimumSize(QtCore.QSize(650, 350))
        MainWindow.setMaximumSize(QtCore.QSize(650, 350))
        MainWindow.setStyleSheet("*{\n"
"    padding:0px;\n"
"    margin:0px;\n"
"    border: none;\n"
"    font: 57 7pt \"Inter Medium\";\n"
"    background: rgb(60, 63, 65);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    background-color: rgb(217, 217, 217);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(52, 129, 200);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.slpash_fram_info = QtWidgets.QFrame(self.frame)
        self.slpash_fram_info.setStyleSheet("")
        self.slpash_fram_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slpash_fram_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slpash_fram_info.setObjectName("slpash_fram_info")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.slpash_fram_info)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.version = QtWidgets.QLabel(self.slpash_fram_info)
        self.version.setMinimumSize(QtCore.QSize(0, 10))
        self.version.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.version.setFont(font)
        self.version.setStyleSheet("")
        self.version.setObjectName("version")
        self.verticalLayout_3.addWidget(self.version)
        self.content_splash = QtWidgets.QFrame(self.slpash_fram_info)
        self.content_splash.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.content_splash.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_splash.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_splash.setObjectName("content_splash")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_splash)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.content_splash)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./img/logo_1.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.content_splash)
        self.autores = QtWidgets.QLabel(self.slpash_fram_info)
        self.autores.setMinimumSize(QtCore.QSize(0, 12))
        self.autores.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.autores.setFont(font)
        self.autores.setStyleSheet("")
        self.autores.setObjectName("autores")
        self.verticalLayout_3.addWidget(self.autores)
        self.verticalLayout.addWidget(self.slpash_fram_info)
        self.splash_frame_bar = QtWidgets.QFrame(self.frame)
        self.splash_frame_bar.setMinimumSize(QtCore.QSize(0, 50))
        self.splash_frame_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.splash_frame_bar.setStyleSheet("")
        self.splash_frame_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splash_frame_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.splash_frame_bar.setObjectName("splash_frame_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.splash_frame_bar)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 5)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splash_infor_mess = QtWidgets.QLabel(self.splash_frame_bar)
        self.splash_infor_mess.setObjectName("splash_infor_mess")
        self.verticalLayout_2.addWidget(self.splash_infor_mess)
        self.high_dir_bar = QtWidgets.QProgressBar(self.splash_frame_bar)
        self.high_dir_bar.setMinimumSize(QtCore.QSize(0, 6))
        self.high_dir_bar.setMaximumSize(QtCore.QSize(16777215, 6))
        self.high_dir_bar.setStyleSheet("")
        self.high_dir_bar.setProperty("value", 24)
        self.high_dir_bar.setTextVisible(False)
        self.high_dir_bar.setObjectName("high_dir_bar")
        self.verticalLayout_2.addWidget(self.high_dir_bar)
        self.low_dir_bar = QtWidgets.QProgressBar(self.splash_frame_bar)
        self.low_dir_bar.setMinimumSize(QtCore.QSize(0, 6))
        self.low_dir_bar.setMaximumSize(QtCore.QSize(16777215, 6))
        self.low_dir_bar.setStyleSheet("")
        self.low_dir_bar.setProperty("value", 24)
        self.low_dir_bar.setTextVisible(False)
        self.low_dir_bar.setObjectName("low_dir_bar")
        self.verticalLayout_2.addWidget(self.low_dir_bar)
        self.verticalLayout.addWidget(self.splash_frame_bar)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.version.setText(_translate("MainWindow", "GenSet Designer V1.0."))
        self.autores.setText(_translate("MainWindow", "Created By: Danilo Ochoa - Jimmy Rincones"))
        self.splash_infor_mess.setText(_translate("MainWindow", "Mensaje de carga"))
