# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skin_load_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 280)
        Form.setMinimumSize(QtCore.QSize(420, 280))
        Form.setMaximumSize(QtCore.QSize(420, 280))
        Form.setStyleSheet("*{\n"
"    padding:0px;\n"
"    margin:0px;\n"
"    border: none;\n"
"    font: 57 8pt \"Inter Medium\";\n"
"    background: rgb(60, 63, 65);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 2px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QFrame(Form)
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(126, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.center_container = QtWidgets.QFrame(self.container)
        self.center_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_container.setObjectName("center_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.center_container)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 125, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.icon_gsd = QtWidgets.QLabel(self.center_container)
        self.icon_gsd.setText("")
        self.icon_gsd.setPixmap(QtGui.QPixmap("./img/logo_4.png"))
        self.icon_gsd.setScaledContents(False)
        self.icon_gsd.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_gsd.setObjectName("icon_gsd")
        self.verticalLayout_2.addWidget(self.icon_gsd)
        self.container_mess_gif = QtWidgets.QFrame(self.center_container)
        self.container_mess_gif.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_mess_gif.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_mess_gif.setObjectName("container_mess_gif")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container_mess_gif)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.load_mess = QtWidgets.QLabel(self.container_mess_gif)
        self.load_mess.setObjectName("load_mess")
        self.horizontalLayout.addWidget(self.load_mess)
        self.preloader = QtWidgets.QLabel(self.container_mess_gif)
        self.preloader.setMinimumSize(QtCore.QSize(20, 20))
        self.preloader.setMaximumSize(QtCore.QSize(20, 20))
        self.preloader.setText("")
        self.preloader.setObjectName("preloader")
        self.horizontalLayout.addWidget(self.preloader)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.container_mess_gif)
        spacerItem4 = QtWidgets.QSpacerItem(20, 124, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_2.addWidget(self.center_container)
        spacerItem5 = QtWidgets.QSpacerItem(126, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.container)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.load_mess.setText(_translate("Form", "Mensaje dinámico de la pantalla de carga."))
