# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skin_project_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(677, 30)
        Form.setMinimumSize(QtCore.QSize(0, 30))
        Form.setMaximumSize(QtCore.QSize(16777215, 30))
        Form.setStyleSheet("*{\n"
"margin: 0px;\n"
"padding: 0px;\n"
"background-color: none;\n"
"border: none;\n"
"}\n"
"\n"
"#container{\n"
"    border: 1px solid rgba(0, 0, 0, 120);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"#eliminar{\n"
"    border: none;\n"
"padding: 2px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"#eliminar:hover{\n"
"    background-color: rgb(167, 167, 167);\n"
"}\n"
"#eliminar:pressed{\n"
"    background-color: rgb(130, 130, 130);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QFrame(Form)
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout.setContentsMargins(10, 2, 10, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nombre_proyecto = QtWidgets.QLabel(self.container)
        self.nombre_proyecto.setText("")
        self.nombre_proyecto.setObjectName("nombre_proyecto")
        self.horizontalLayout.addWidget(self.nombre_proyecto)
        spacerItem = QtWidgets.QSpacerItem(207, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ruta_proyecto = QtWidgets.QLabel(self.container)
        self.ruta_proyecto.setText("")
        self.ruta_proyecto.setObjectName("ruta_proyecto")
        self.horizontalLayout.addWidget(self.ruta_proyecto)
        spacerItem1 = QtWidgets.QSpacerItem(207, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.fecha_modificacion = QtWidgets.QLabel(self.container)
        self.fecha_modificacion.setText("")
        self.fecha_modificacion.setObjectName("fecha_modificacion")
        self.horizontalLayout.addWidget(self.fecha_modificacion)
        self.eliminar = QtWidgets.QToolButton(self.container)
        self.eliminar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eliminar.setIcon(icon)
        self.eliminar.setIconSize(QtCore.QSize(10, 10))
        self.eliminar.setObjectName("eliminar")
        self.horizontalLayout.addWidget(self.eliminar)
        self.verticalLayout.addWidget(self.container)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
