# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skin_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        MainWindow.setMinimumSize(QtCore.QSize(700, 700))
        MainWindow.setMaximumSize(QtCore.QSize(700, 700))
        MainWindow.setStyleSheet("QMainWindow { \n"
"    background-color: rgb(156, 156, 156);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    border: none;\n"
"padding: 0px;\n"
"margin: 0px;\n"
"font: 57 8pt \"Inter Medium\";\n"
"background: rgb(60, 63, 65);\n"
"}\n"
"#center_frame{\n"
"    border: 2px solid rgb(86, 88, 89);\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgb(42, 42, 43);\n"
"    border: 1px solid rgb(86, 88, 89);\n"
"    border-radius: 5px;\n"
"    height: 25px; \n"
"    color: rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(52, 129, 200);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 1px solid white;\n"
"}\n"
"QToolButton{\n"
"    background-color: rgb(42, 42, 43);\n"
"    border: 2px solid rgb(52, 129, 200);\n"
"    border-radius: 5px;\n"
"    height: 35px;\n"
"    width: 220px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: rgb(52, 129, 200);\n"
"}\n"
"QToolButton:pressed{\n"
"    background-color: rgb(42, 105, 161);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.background)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(182, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.center_frame = QtWidgets.QFrame(self.background)
        self.center_frame.setMinimumSize(QtCore.QSize(300, 500))
        self.center_frame.setMaximumSize(QtCore.QSize(300, 500))
        self.center_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_frame.setObjectName("center_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.center_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.frame = QtWidgets.QFrame(self.center_frame)
        self.frame.setMinimumSize(QtCore.QSize(250, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.name_edit = QtWidgets.QLineEdit(self.frame)
        self.name_edit.setText("")
        self.name_edit.setObjectName("name_edit")
        self.verticalLayout_2.addWidget(self.name_edit)
        self.apellido_edit = QtWidgets.QLineEdit(self.frame)
        self.apellido_edit.setText("")
        self.apellido_edit.setObjectName("apellido_edit")
        self.verticalLayout_2.addWidget(self.apellido_edit)
        self.pais_edit = QtWidgets.QLineEdit(self.frame)
        self.pais_edit.setText("")
        self.pais_edit.setObjectName("pais_edit")
        self.verticalLayout_2.addWidget(self.pais_edit)
        self.correo_edit = QtWidgets.QLineEdit(self.frame)
        self.correo_edit.setObjectName("correo_edit")
        self.verticalLayout_2.addWidget(self.correo_edit)
        self.institucion_edit = QtWidgets.QLineEdit(self.frame)
        self.institucion_edit.setObjectName("institucion_edit")
        self.verticalLayout_2.addWidget(self.institucion_edit)
        self.profesion_edit = QtWidgets.QLineEdit(self.frame)
        self.profesion_edit.setObjectName("profesion_edit")
        self.verticalLayout_2.addWidget(self.profesion_edit)
        spacerItem5 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("QLabel{\n"
"    font-size: 6pt;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_acept = QtWidgets.QToolButton(self.frame_2)
        self.button_acept.setStyleSheet("#button_acept{\n"
"    font-weight: bold;\n"
"}")
        self.button_acept.setObjectName("button_acept")
        self.horizontalLayout_3.addWidget(self.button_acept)
        self.verticalLayout_2.addWidget(self.frame_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_2.addWidget(self.frame)
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.horizontalLayout.addWidget(self.center_frame)
        spacerItem8 = QtWidgets.QSpacerItem(182, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.background)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Logo"))
        self.name_edit.setPlaceholderText(_translate("MainWindow", "Nombre real"))
        self.apellido_edit.setPlaceholderText(_translate("MainWindow", "Apellido"))
        self.pais_edit.setPlaceholderText(_translate("MainWindow", "País"))
        self.correo_edit.setPlaceholderText(_translate("MainWindow", "Correo electrónico"))
        self.institucion_edit.setPlaceholderText(_translate("MainWindow", "Institución"))
        self.profesion_edit.setPlaceholderText(_translate("MainWindow", "Profesión"))
        self.label_2.setText(_translate("MainWindow", "Todos los campos son obligatorios."))
        self.button_acept.setText(_translate("MainWindow", "Registrarse"))
