# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skin_nuevo_genset.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 521)
        Form.setStyleSheet("*{\n"
"    padding:0px;\n"
"    margin:0px;\n"
"    border: none;\n"
"    font: 57 8pt \"Inter Medium\";\n"
"    background: rgb(60, 63, 65);\n"
"    border-radius: 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"#titulo_nuevo{\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#From{\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#cerrar_nuevo{\n"
"    image: url(img/cerrar_white.png);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"background: rgb(60, 63, 65);\n"
"}\n"
"\n"
"#cerrar_nuevo:hover{\n"
"    background-color: rgb(42, 42, 43);\n"
"}\n"
"\n"
"#base_frame{\n"
"    background-color: rgb(60, 63, 65);\n"
"    border-radius: 6px;\n"
"    border: 1px solid rgb(86, 88, 89);\n"
"}\n"
"QLabel{\n"
"    font: 57 10pt \"Inter Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QToolButton, QPushButton{\n"
"    background-color: rgb(196, 198, 201);\n"
"    font: 57 10pt \"Inter Medium\";\n"
"padding: 2px;\n"
"    border-radius: 2px;\n"
"border: 1px solid rgba(112, 112, 112, 150);\n"
"    color: black;\n"
"}\n"
"\n"
"QToolButton:hover, QPushButton:hover{\n"
"    background-color: rgb(52, 129, 200);\n"
"}\n"
"\n"
"QToolButton:pressed, QPushButton:pressed{\n"
"    background-color: rgb(104, 104, 104);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"   background-color: rgb(42, 42, 43);\n"
"    border: 1px solid rgb(86, 88, 89);\n"
"    border-radius: 5px;\n"
"   color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(52, 129, 200);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 1px solid white;\n"
"}\n"
"/*Etilos combox*/\n"
"QComboBox {\n"
"   background-color: rgb(42, 42, 43);\n"
"    border: 1px solid rgb(86, 88, 89);\n"
"    border-radius: 5px;\n"
"   color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"}\n"
"QComboBox:hover, QComboBox:focus {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 4px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border: 0px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down:hover{\n"
"     background-color: #0078D7;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(img/down.png);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    margin: 10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"    border: 1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 2px;\n"
"    outline: 0px;\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"/*Estilos para la ScrollBar*/\n"
"QScrollBar:vertical {     \n"
"       border: 1px solid #999999;\n"
"        background:white;\n"
"        width:10px;\n"
"        border-radius: 4px;\n"
"        margin: 0px 0px 0px 0px;\n"
"    }\n"
"    QScrollBar::handle:vertical {\n"
"        background: rgb(42, 42, 43);\n"
"        min-height: 0px;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QScrollBar::add-line:vertical {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop: 0 rgb(32, 47, 130), stop: 0.5 rgb(32, 47, 130),  stop:1 rgb(32, 47, 130));\n"
"        height: 0px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::sub-line:vertical {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop: 0  rgb(32, 47, 130), stop: 0.5 rgb(32, 47, 130),  stop:1 rgb(32, 47, 130));\n"
"        height: 0 px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.base_frame = QtWidgets.QFrame(Form)
        self.base_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.base_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.base_frame.setObjectName("base_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.base_frame)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container_nuevo_titulo = QtWidgets.QFrame(self.base_frame)
        self.container_nuevo_titulo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.container_nuevo_titulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container_nuevo_titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_nuevo_titulo.setObjectName("container_nuevo_titulo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.container_nuevo_titulo)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.container_nuevo_titulo)
        self.label.setMinimumSize(QtCore.QSize(30, 30))
        self.label.setMaximumSize(QtCore.QSize(30, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./img/logo_7.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.titulo_nuevo = QtWidgets.QLabel(self.container_nuevo_titulo)
        self.titulo_nuevo.setObjectName("titulo_nuevo")
        self.horizontalLayout_2.addWidget(self.titulo_nuevo)
        spacerItem = QtWidgets.QSpacerItem(282, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cerrar_nuevo = QtWidgets.QToolButton(self.container_nuevo_titulo)
        self.cerrar_nuevo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/cerrar_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cerrar_nuevo.setIcon(icon)
        self.cerrar_nuevo.setObjectName("cerrar_nuevo")
        self.horizontalLayout_2.addWidget(self.cerrar_nuevo)
        self.verticalLayout.addWidget(self.container_nuevo_titulo)
        self.frame_2 = QtWidgets.QFrame(self.base_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.datos = QtWidgets.QFrame(self.frame_2)
        self.datos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.datos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.datos.setObjectName("datos")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.datos)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_content = QtWidgets.QFrame(self.datos)
        self.left_content.setMaximumSize(QtCore.QSize(250, 16777215))
        self.left_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_content.setObjectName("left_content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_content)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.left_content)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.voltaje = QtWidgets.QLineEdit(self.frame_5)
        self.voltaje.setMaximumSize(QtCore.QSize(80, 16777215))
        self.voltaje.setObjectName("voltaje")
        self.horizontalLayout_5.addWidget(self.voltaje)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.left_content)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.left_content)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_7.addWidget(self.lineEdit_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame = QtWidgets.QFrame(self.left_content)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_8.addWidget(self.lineEdit_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_8 = QtWidgets.QFrame(self.left_content)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.comboBox = QtWidgets.QComboBox(self.frame_8)
        self.comboBox.setMinimumSize(QtCore.QSize(30, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.left_content)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_10.addWidget(self.lineEdit_4)
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_10.addWidget(self.lineEdit_5)
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_10.addWidget(self.lineEdit_6)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.horizontalLayout_4.addWidget(self.left_content)
        self.frame_4 = QtWidgets.QFrame(self.datos)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_11)
        self.comboBox_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_2)
        spacerItem6 = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_13.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.frame_12)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_13.addWidget(self.lineEdit_9)
        spacerItem7 = QtWidgets.QSpacerItem(94, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_4)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_15.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.frame_13)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_15.addWidget(self.lineEdit_11)
        spacerItem8 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.verticalLayout_4.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_4)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_14.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_14.addWidget(self.lineEdit_10)
        spacerItem9 = QtWidgets.QSpacerItem(62, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem9)
        self.verticalLayout_4.addWidget(self.frame_14)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_11.addWidget(self.lineEdit_7)
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_11.addWidget(self.lineEdit_8)
        spacerItem10 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.frame_15 = QtWidgets.QFrame(self.frame_4)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_16.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.frame_15)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_16.addWidget(self.lineEdit_12)
        self.verticalLayout_4.addWidget(self.frame_15)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.datos)
        self.tabla = QtWidgets.QFrame(self.frame_2)
        self.tabla.setMinimumSize(QtCore.QSize(0, 200))
        self.tabla.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tabla.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tabla.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tabla.setObjectName("tabla")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabla)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.tabla)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.frame_16 = QtWidgets.QFrame(self.tabla)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem11)
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_17.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.tabla_input = QtWidgets.QTableWidget(self.frame_17)
        self.tabla_input.setMaximumSize(QtCore.QSize(16777215, 135))
        self.tabla_input.setStyleSheet("QHeaderView::section{\n"
"    background: rgb(60, 63, 65);\n"
"    border: 1px solid rgba(112, 112, 112, 150);\n"
"}\n"
"\n"
"QTableCornerButton::section{\n"
"    background: rgb(60, 63, 65);\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: 1px solid rgba(112, 112, 112, 150);\n"
"    border-radius: 5px;\n"
"    gridline-color: rgba(112, 112, 112, 150);\n"
"text-align: center; vertical-align: middle;\n"
"}\n"
"\n"
"QScrollBar:vertical {     \n"
"       border: 1px solid #999999;\n"
"        background:white;\n"
"        width:10px;\n"
"        border-radius: 2px;\n"
"        margin: 0px 0px 0px 0px;\n"
"    }\n"
"    QScrollBar::handle:vertical {\n"
"        background: rgb(42, 42, 43);\n"
"        min-height: 0px;\n"
"        border-radius: 2px;\n"
"    }\n"
"    QScrollBar::add-line:vertical {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop: 0 rgb(32, 47, 130), stop: 0.5 rgb(32, 47, 130),  stop:1 rgb(32, 47, 130));\n"
"        height: 0px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::sub-line:vertical {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop: 0  rgb(32, 47, 130), stop: 0.5 rgb(32, 47, 130),  stop:1 rgb(32, 47, 130));\n"
"        height: 0 px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"QScrollBar:horizontal {     \n"
"       border: 1px solid #999999;\n"
"        background:white;\n"
"        height:10px;\n"
"        border-radius: 2px;\n"
"        margin: 0px 0px 0px 0px;\n"
"    }\n"
"    QScrollBar::handle:horizontal {\n"
"        background: rgb(42, 42, 43);\n"
"        min-height: 0px;\n"
"        border-radius: 2px;\n"
"    }\n"
"    QScrollBar::add-line:horizontal {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop: 0 rgb(32, 47, 130), stop: 0.5 rgb(32, 47, 130),  stop:1 rgb(32, 47, 130));\n"
"        width: 0px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::sub-line:horizontal {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop: 0  rgb(32, 47, 130), stop: 0.5 rgb(32, 47, 130),  stop:1 rgb(32, 47, 130));\n"
"        width: 0 px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }")
        self.tabla_input.setObjectName("tabla_input")
        self.tabla_input.setColumnCount(13)
        self.tabla_input.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_input.setHorizontalHeaderItem(12, item)
        self.tabla_input.horizontalHeader().setSortIndicatorShown(False)
        self.tabla_input.horizontalHeader().setStretchLastSection(True)
        self.tabla_input.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_17.addWidget(self.tabla_input)
        self.verticalLayout_6.addWidget(self.frame_17)
        spacerItem12 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem12)
        self.verticalLayout_5.addWidget(self.frame_16)
        self.verticalLayout_2.addWidget(self.tabla)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.base_frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem13 = QtWidgets.QSpacerItem(432, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.toolButton = QtWidgets.QToolButton(self.frame_3)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_3.addWidget(self.toolButton)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.base_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titulo_nuevo.setText(_translate("Form", "Ingresar nuevo generador"))
        self.label_2.setText(_translate("Form", "Voltaje"))
        self.label_3.setText(_translate("Form", "Potencia kVA"))
        self.label_4.setText(_translate("Form", "Potencia kW"))
        self.label_5.setText(_translate("Form", "Frecuencia"))
        self.label_6.setText(_translate("Form", "Fases"))
        self.comboBox.setItemText(0, _translate("Form", "1"))
        self.comboBox.setItemText(1, _translate("Form", "3"))
        self.label_7.setText(_translate("Form", "Xd"))
        self.label_8.setText(_translate("Form", "Xd\'"))
        self.label_9.setText(_translate("Form", "Xd\'\'"))
        self.label_12.setText(_translate("Form", "Aislamiento"))
        self.comboBox_2.setItemText(0, _translate("Form", "A"))
        self.comboBox_2.setItemText(1, _translate("Form", "B"))
        self.comboBox_2.setItemText(2, _translate("Form", "F"))
        self.comboBox_2.setItemText(3, _translate("Form", "H"))
        self.label_13.setText(_translate("Form", "Modelo"))
        self.label_15.setText(_translate("Form", "Fabricante"))
        self.label_14.setText(_translate("Form", "Combustible"))
        self.label_10.setText(_translate("Form", "Xq"))
        self.label_11.setText(_translate("Form", "Xq\'\'"))
        self.label_16.setText(_translate("Form", "URL"))
        self.label_17.setText(_translate("Form", "Curva de volt. dip vs. potencia"))
        item = self.tabla_input.verticalHeaderItem(0)
        item.setText(_translate("Form", "V1"))
        item = self.tabla_input.verticalHeaderItem(1)
        item.setText(_translate("Form", "V2"))
        item = self.tabla_input.verticalHeaderItem(2)
        item.setText(_translate("Form", "V3"))
        item = self.tabla_input.horizontalHeaderItem(0)
        item.setText(_translate("Form", "0"))
        item = self.tabla_input.horizontalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tabla_input.horizontalHeaderItem(2)
        item.setText(_translate("Form", "5"))
        item = self.tabla_input.horizontalHeaderItem(3)
        item.setText(_translate("Form", "7"))
        item = self.tabla_input.horizontalHeaderItem(4)
        item.setText(_translate("Form", "10"))
        item = self.tabla_input.horizontalHeaderItem(5)
        item.setText(_translate("Form", "12"))
        item = self.tabla_input.horizontalHeaderItem(6)
        item.setText(_translate("Form", "15"))
        item = self.tabla_input.horizontalHeaderItem(7)
        item.setText(_translate("Form", "17"))
        item = self.tabla_input.horizontalHeaderItem(8)
        item.setText(_translate("Form", "20"))
        item = self.tabla_input.horizontalHeaderItem(9)
        item.setText(_translate("Form", "22"))
        item = self.tabla_input.horizontalHeaderItem(10)
        item.setText(_translate("Form", "25"))
        item = self.tabla_input.horizontalHeaderItem(11)
        item.setText(_translate("Form", "27"))
        item = self.tabla_input.horizontalHeaderItem(12)
        item.setText(_translate("Form", "30"))
        self.toolButton.setText(_translate("Form", "Aceptar"))
