# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skin_data_dim.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(470, 450)
        Form.setMinimumSize(QtCore.QSize(470, 350))
        Form.setMaximumSize(QtCore.QSize(470, 450))
        Form.setStyleSheet("*{\n"
"    padding:0px;\n"
"    margin:0px;\n"
"    border: none;\n"
"    font: 57 8pt \"Inter Medium\";\n"
"    background: rgb(60, 63, 65);\n"
"    border-radius: 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"#From{\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#base_frame{\n"
"    background-color: rgb(60, 63, 65);\n"
"    border-radius: 6px;\n"
"    border: 1px solid rgb(86, 88, 89);\n"
"}\n"
"QLabel{\n"
"    font: 57 11pt \"Inter Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QToolButton, QPushButton{\n"
"    background-color: rgb(196, 198, 201);\n"
"    font: 57 10pt \"Inter Medium\";\n"
"padding: 2px;\n"
"    border-radius: 2px;\n"
"border: 1px solid rgba(112, 112, 112, 150);\n"
"    color: black;\n"
"}\n"
"\n"
"QToolButton:hover, QPushButton:hover{\n"
"    background-color: rgb(52, 129, 200);\n"
"}\n"
"\n"
"QToolButton:pressed, QPushButton:pressed{\n"
"    background-color: rgb(104, 104, 104);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#close_button{\n"
"    image: url(img/cerrar_white.png);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"background: rgb(60, 63, 65);\n"
"}\n"
"\n"
"#close_button:hover{\n"
"    background-color: rgb(42, 42, 43);\n"
"}\n"
"\n"
"/*Estilos QLineEdit*/\n"
"QLineEdit{\n"
"   background-color: rgb(42, 42, 43);\n"
"    border: 1px solid rgb(86, 88, 89);\n"
"    border-radius: 5px;\n"
"   color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 1px solid rgb(52, 129, 200);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 1px solid white;\n"
"}\n"
"QCheckBox::indicator:hover, QLineEdit:hover, QLineEdit:focus {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 4px;\n"
"}\n"
"/*Etilos combox*/\n"
"QComboBox {\n"
"   background-color: rgb(42, 42, 43);\n"
"    border: 1px solid rgb(86, 88, 89);\n"
"    border-radius: 5px;\n"
"   color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"}\n"
"QComboBox:hover, QComboBox:focus {\n"
"    border: 2px solid #0078D7;\n"
"    border-radius: 4px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border: 0px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down:hover{\n"
"     background-color: #0078D7;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(img/down.png);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    margin: 10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"    border: 1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 2px;\n"
"    outline: 0px;\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"/*Estilos para la ScrollBar*/\n"
"QScrollBar:vertical {     \n"
"       border: 1px solid #999999;\n"
"        background:white;\n"
"        width:10px;\n"
"        border-radius: 4px;\n"
"        margin: 0px 0px 0px 0px;\n"
"    }\n"
"    QScrollBar::handle:vertical {\n"
"        background: rgb(42, 42, 43);\n"
"        min-height: 0px;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QScrollBar::add-line:vertical {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop: 0 rgb(32, 47, 130), stop: 0.5 rgb(32, 47, 130),  stop:1 rgb(32, 47, 130));\n"
"        height: 0px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::sub-line:vertical {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop: 0  rgb(32, 47, 130), stop: 0.5 rgb(32, 47, 130),  stop:1 rgb(32, 47, 130));\n"
"        height: 0 px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.base_frame = QtWidgets.QFrame(Form)
        self.base_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.base_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.base_frame.setObjectName("base_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.base_frame)
        self.verticalLayout_2.setContentsMargins(15, 10, 15, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_frame = QtWidgets.QFrame(self.base_frame)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(414, 15, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.close_button = QtWidgets.QToolButton(self.title_frame)
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_3.addWidget(self.close_button)
        self.verticalLayout_2.addWidget(self.title_frame)
        self.top_container = QtWidgets.QFrame(self.base_frame)
        self.top_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.top_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_container.setObjectName("top_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_container)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icono = QtWidgets.QLabel(self.top_container)
        self.icono.setMaximumSize(QtCore.QSize(50, 50))
        self.icono.setText("")
        self.icono.setPixmap(QtGui.QPixmap("./img/logo_7.png"))
        self.icono.setScaledContents(True)
        self.icono.setObjectName("icono")
        self.horizontalLayout.addWidget(self.icono)
        self.titulo = QtWidgets.QLabel(self.top_container)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.horizontalLayout.addWidget(self.titulo)
        self.verticalLayout_2.addWidget(self.top_container)
        self.name_project = QtWidgets.QFrame(self.base_frame)
        self.name_project.setMinimumSize(QtCore.QSize(0, 25))
        self.name_project.setStyleSheet("QLabel{\n"
"    font-size: 8pt;\n"
"}")
        self.name_project.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_project.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_project.setObjectName("name_project")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.name_project)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.name_project)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.nombre_proyecto = QtWidgets.QLineEdit(self.name_project)
        self.nombre_proyecto.setMinimumSize(QtCore.QSize(200, 0))
        self.nombre_proyecto.setMaximumSize(QtCore.QSize(330, 16777215))
        self.nombre_proyecto.setObjectName("nombre_proyecto")
        self.horizontalLayout_5.addWidget(self.nombre_proyecto)
        self.verticalLayout_2.addWidget(self.name_project)
        self.descripcion_contacto = QtWidgets.QFrame(self.base_frame)
        self.descripcion_contacto.setMinimumSize(QtCore.QSize(0, 50))
        self.descripcion_contacto.setStyleSheet("QLabel{\n"
"    font-size: 8pt;\n"
"}")
        self.descripcion_contacto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descripcion_contacto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.descripcion_contacto.setObjectName("descripcion_contacto")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.descripcion_contacto)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_14 = QtWidgets.QFrame(self.descripcion_contacto)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        self.descripcion = QtWidgets.QLineEdit(self.frame_14)
        self.descripcion.setObjectName("descripcion")
        self.horizontalLayout_18.addWidget(self.descripcion)
        self.verticalLayout_5.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.descripcion_contacto)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_19.addWidget(self.label_15)
        self.contacto = QtWidgets.QLineEdit(self.frame_15)
        self.contacto.setObjectName("contacto")
        self.horizontalLayout_19.addWidget(self.contacto)
        spacerItem1 = QtWidgets.QSpacerItem(184, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.frame_15)
        self.verticalLayout_2.addWidget(self.descripcion_contacto)
        self.data_container = QtWidgets.QFrame(self.base_frame)
        self.data_container.setMinimumSize(QtCore.QSize(0, 0))
        self.data_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.data_container.setStyleSheet("QLabel{\n"
"    font-size: 8pt;\n"
"}")
        self.data_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.data_container.setObjectName("data_container")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.data_container)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left = QtWidgets.QFrame(self.data_container)
        self.left.setMaximumSize(QtCore.QSize(250, 16777215))
        self.left.setStyleSheet("")
        self.left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setObjectName("left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.left)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.sistem_voltaje = QtWidgets.QComboBox(self.frame_2)
        self.sistem_voltaje.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sistem_voltaje.setObjectName("sistem_voltaje")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.sistem_voltaje.addItem("")
        self.horizontalLayout_6.addWidget(self.sistem_voltaje)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.left)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.combo_fases = QtWidgets.QComboBox(self.frame_4)
        self.combo_fases.setMaximumSize(QtCore.QSize(40, 16777215))
        self.combo_fases.setObjectName("combo_fases")
        self.combo_fases.addItem("")
        self.combo_fases.addItem("")
        self.horizontalLayout_7.addWidget(self.combo_fases)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.left)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.frecuencia_sistema = QtWidgets.QComboBox(self.frame_3)
        self.frecuencia_sistema.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frecuencia_sistema.setObjectName("frecuencia_sistema")
        self.frecuencia_sistema.addItem("")
        self.frecuencia_sistema.addItem("")
        self.horizontalLayout_8.addWidget(self.frecuencia_sistema)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_6 = QtWidgets.QFrame(self.left)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.altura_msnm = QtWidgets.QLineEdit(self.frame_6)
        self.altura_msnm.setMaximumSize(QtCore.QSize(60, 16777215))
        self.altura_msnm.setObjectName("altura_msnm")
        self.horizontalLayout_9.addWidget(self.altura_msnm)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.left)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.temperatura_sistema = QtWidgets.QLineEdit(self.frame_5)
        self.temperatura_sistema.setMaximumSize(QtCore.QSize(60, 16777215))
        self.temperatura_sistema.setObjectName("temperatura_sistema")
        self.horizontalLayout_10.addWidget(self.temperatura_sistema)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame = QtWidgets.QFrame(self.left)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.thd = QtWidgets.QLineEdit(self.frame)
        self.thd.setMaximumSize(QtCore.QSize(60, 16777215))
        self.thd.setObjectName("thd")
        self.horizontalLayout_17.addWidget(self.thd)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4.addWidget(self.left)
        self.right = QtWidgets.QFrame(self.data_container)
        self.right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right.setObjectName("right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.right)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.tiempo_servicio = QtWidgets.QLineEdit(self.frame_7)
        self.tiempo_servicio.setMaximumSize(QtCore.QSize(60, 16777215))
        self.tiempo_servicio.setObjectName("tiempo_servicio")
        self.horizontalLayout_11.addWidget(self.tiempo_servicio)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.right)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.porcentaje_reserva = QtWidgets.QLineEdit(self.frame_8)
        self.porcentaje_reserva.setMaximumSize(QtCore.QSize(60, 16777215))
        self.porcentaje_reserva.setObjectName("porcentaje_reserva")
        self.horizontalLayout_12.addWidget(self.porcentaje_reserva)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.right)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.voltaje_dip = QtWidgets.QLineEdit(self.frame_10)
        self.voltaje_dip.setMaximumSize(QtCore.QSize(60, 16777215))
        self.voltaje_dip.setObjectName("voltaje_dip")
        self.horizontalLayout_13.addWidget(self.voltaje_dip)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.right)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_14.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.frame_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        self.tipo_combustible = QtWidgets.QComboBox(self.frame_9)
        self.tipo_combustible.setObjectName("tipo_combustible")
        self.tipo_combustible.addItem("")
        self.tipo_combustible.addItem("")
        self.tipo_combustible.addItem("")
        self.horizontalLayout_14.addWidget(self.tipo_combustible)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_11 = QtWidgets.QFrame(self.right)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_15.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.ciclo_trabajo = QtWidgets.QComboBox(self.frame_11)
        self.ciclo_trabajo.setObjectName("ciclo_trabajo")
        self.ciclo_trabajo.addItem("")
        self.ciclo_trabajo.addItem("")
        self.ciclo_trabajo.addItem("")
        self.horizontalLayout_15.addWidget(self.ciclo_trabajo)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.right)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_16.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.frame_12)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.iso_8528 = QtWidgets.QComboBox(self.frame_12)
        self.iso_8528.setMaximumSize(QtCore.QSize(60, 16777215))
        self.iso_8528.setObjectName("iso_8528")
        self.iso_8528.addItem("")
        self.iso_8528.addItem("")
        self.iso_8528.addItem("")
        self.horizontalLayout_16.addWidget(self.iso_8528)
        self.verticalLayout_4.addWidget(self.frame_12)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_4.addWidget(self.right)
        self.verticalLayout_2.addWidget(self.data_container)
        self.buton_frames = QtWidgets.QFrame(self.base_frame)
        self.buton_frames.setMaximumSize(QtCore.QSize(16777215, 40))
        self.buton_frames.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buton_frames.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buton_frames.setObjectName("buton_frames")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buton_frames)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(406, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.siguiente_dim = QtWidgets.QToolButton(self.buton_frames)
        self.siguiente_dim.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/siguiente_loads.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.siguiente_dim.setIcon(icon)
        self.siguiente_dim.setObjectName("siguiente_dim")
        self.horizontalLayout_2.addWidget(self.siguiente_dim)
        self.verticalLayout_2.addWidget(self.buton_frames)
        self.verticalLayout.addWidget(self.base_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titulo.setText(_translate("Form", "Dimensionar GenSet: datos generales del proyecto."))
        self.label.setText(_translate("Form", "Nombre del proyecto"))
        self.label_14.setText(_translate("Form", "Descripción"))
        self.label_15.setText(_translate("Form", "Contacto"))
        self.label_2.setText(_translate("Form", "Voltaje"))
        self.sistem_voltaje.setItemText(0, _translate("Form", "115"))
        self.sistem_voltaje.setItemText(1, _translate("Form", "120"))
        self.sistem_voltaje.setItemText(2, _translate("Form", "208"))
        self.sistem_voltaje.setItemText(3, _translate("Form", "220"))
        self.sistem_voltaje.setItemText(4, _translate("Form", "230"))
        self.sistem_voltaje.setItemText(5, _translate("Form", "240"))
        self.sistem_voltaje.setItemText(6, _translate("Form", "460"))
        self.sistem_voltaje.setItemText(7, _translate("Form", "480"))
        self.sistem_voltaje.setItemText(8, _translate("Form", "575"))
        self.sistem_voltaje.setItemText(9, _translate("Form", "600"))
        self.sistem_voltaje.setItemText(10, _translate("Form", "2400"))
        self.sistem_voltaje.setItemText(11, _translate("Form", "4160"))
        self.sistem_voltaje.setItemText(12, _translate("Form", "4800"))
        self.sistem_voltaje.setItemText(13, _translate("Form", "6900"))
        self.sistem_voltaje.setItemText(14, _translate("Form", "8320"))
        self.sistem_voltaje.setItemText(15, _translate("Form", "12000"))
        self.sistem_voltaje.setItemText(16, _translate("Form", "12470"))
        self.sistem_voltaje.setItemText(17, _translate("Form", "13200"))
        self.sistem_voltaje.setItemText(18, _translate("Form", "13800"))
        self.label_3.setText(_translate("Form", "Fases"))
        self.combo_fases.setItemText(0, _translate("Form", "1"))
        self.combo_fases.setItemText(1, _translate("Form", "3"))
        self.label_4.setText(_translate("Form", "Frecuencia"))
        self.frecuencia_sistema.setItemText(0, _translate("Form", "50"))
        self.frecuencia_sistema.setItemText(1, _translate("Form", "60"))
        self.label_5.setText(_translate("Form", "Altura (m.s.n.m)"))
        self.label_6.setText(_translate("Form", "Temperatura (°C)"))
        self.label_13.setText(_translate("Form", "THD%"))
        self.label_7.setText(_translate("Form", "Tiempo de servicio anual (h)"))
        self.label_8.setText(_translate("Form", "Porcentaje de reserva"))
        self.label_9.setText(_translate("Form", "Voltaje dip."))
        self.label_10.setText(_translate("Form", "Tipo de combustible"))
        self.tipo_combustible.setItemText(0, _translate("Form", "Gas natural"))
        self.tipo_combustible.setItemText(1, _translate("Form", "Gasoil"))
        self.tipo_combustible.setItemText(2, _translate("Form", "Diesel"))
        self.label_11.setText(_translate("Form", "Ciclo de trabajo"))
        self.ciclo_trabajo.setItemText(0, _translate("Form", "Standby"))
        self.ciclo_trabajo.setItemText(1, _translate("Form", "Prime"))
        self.ciclo_trabajo.setItemText(2, _translate("Form", "Continuos"))
        self.label_12.setText(_translate("Form", "ISO 8528"))
        self.iso_8528.setItemText(0, _translate("Form", "G1"))
        self.iso_8528.setItemText(1, _translate("Form", "G2"))
        self.iso_8528.setItemText(2, _translate("Form", "G3"))
